import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class CountryService {
  getCountries(): Observable<any[]> {
    return of([
      { id: '1', name: 'საქართველო', prefix: '+995' },
      { id: '2', name: 'Afghanistan', prefix: '+93' },
      { id: '3', name: 'Albania', prefix: '+355' },
      { id: '4', name: 'Algeria', prefix: '+213' },
      { id: '5', name: 'Andorra', prefix: '+376' },
      { id: '6', name: 'Angola', prefix: '+244' },
      { id: '7', name: 'Argentina', prefix: '+54' },
      { id: '8', name: 'Armenia', prefix: '+374' },
      { id: '9', name: 'Australia', prefix: '+61' },
      { id: '10', name: 'Austria', prefix: '+43' },
      { id: '11', name: 'Azerbaijan', prefix: '+994' },
      { id: '12', name: 'Bahamas', prefix: '+1-242' },
      { id: '13', name: 'Bahrain', prefix: '+973' },
      { id: '14', name: 'Bangladesh', prefix: '+880' },
      { id: '15', name: 'Barbados', prefix: '+1-246' },
      { id: '16', name: 'Belarus', prefix: '+375' },
      { id: '17', name: 'Belgium', prefix: '+32' },
      { id: '18', name: 'Belize', prefix: '+501' },
      { id: '19', name: 'Benin', prefix: '+229' },
      { id: '20', name: 'Bhutan', prefix: '+975' },
      { id: '21', name: 'Bolivia', prefix: '+591' },
      { id: '22', name: 'Bosnia and Herzegovina', prefix: '+387' },
      { id: '23', name: 'Botswana', prefix: '+267' },
      { id: '24', name: 'Brazil', prefix: '+55' },
      { id: '25', name: 'Brunei', prefix: '+673' },
      { id: '26', name: 'Bulgaria', prefix: '+359' },
      { id: '27', name: 'Burkina Faso', prefix: '+226' },
      { id: '28', name: 'Burundi', prefix: '+257' },
      { id: '29', name: 'Cambodia', prefix: '+855' },
      { id: '30', name: 'Cameroon', prefix: '+237' },
      { id: '31', name: 'Canada', prefix: '+1' },
      { id: '32', name: 'Cape Verde', prefix: '+238' },
      { id: '33', name: 'Central African Republic', prefix: '+236' },
      { id: '34', name: 'Chad', prefix: '+235' },
      { id: '35', name: 'Chile', prefix: '+56' },
      { id: '36', name: 'China', prefix: '+86' },
      { id: '37', name: 'Colombia', prefix: '+57' },
      { id: '38', name: 'Comoros', prefix: '+269' },
      { id: '39', name: 'Congo', prefix: '+242' },
      { id: '40', name: 'Congo (DRC)', prefix: '+243' },
      { id: '41', name: 'Costa Rica', prefix: '+506' },
      { id: '42', name: 'Croatia', prefix: '+385' },
      { id: '43', name: 'Cuba', prefix: '+53' },
      { id: '44', name: 'Cyprus', prefix: '+357' },
      { id: '45', name: 'Czech Republic', prefix: '+420' },
      { id: '46', name: 'Denmark', prefix: '+45' },
      { id: '47', name: 'Djibouti', prefix: '+253' },
      { id: '48', name: 'Dominica', prefix: '+1-767' },
      { id: '49', name: 'Dominican Republic', prefix: '+1-809' },
      { id: '50', name: 'Ecuador', prefix: '+593' },
      { id: '51', name: 'Egypt', prefix: '+20' },
      { id: '52', name: 'El Salvador', prefix: '+503' },
    { id: '53', name: 'Equatorial Guinea', prefix: '+240' },
    { id: '54', name: 'Eritrea', prefix: '+291' },
    { id: '55', name: 'Estonia', prefix: '+372' },
    { id: '56', name: 'Eswatini', prefix: '+268' },
    { id: '57', name: 'Ethiopia', prefix: '+251' },
    { id: '58', name: 'Fiji', prefix: '+679' },
    { id: '59', name: 'Finland', prefix: '+358' },
    { id: '60', name: 'France', prefix: '+33' },
    { id: '61', name: 'Gabon', prefix: '+241' },
    { id: '62', name: 'Gambia', prefix: '+220' },
    { id: '63', name: 'Germany', prefix: '+49' },
    { id: '64', name: 'Ghana', prefix: '+233' },
    { id: '65', name: 'Greece', prefix: '+30' },
    { id: '66', name: 'Grenada', prefix: '+1-473' },
    { id: '67', name: 'Guatemala', prefix: '+502' },
    { id: '68', name: 'Guinea', prefix: '+224' },
    { id: '69', name: 'Guinea-Bissau', prefix: '+245' },
    { id: '70', name: 'Guyana', prefix: '+592' },
    { id: '71', name: 'Haiti', prefix: '+509' },
    { id: '72', name: 'Honduras', prefix: '+504' },
    { id: '73', name: 'Hungary', prefix: '+36' },
    { id: '74', name: 'Iceland', prefix: '+354' },
    { id: '75', name: 'India', prefix: '+91' },
    { id: '76', name: 'Indonesia', prefix: '+62' },
    { id: '77', name: 'Iran', prefix: '+98' },
    { id: '78', name: 'Iraq', prefix: '+964' },
    { id: '79', name: 'Ireland', prefix: '+353' },
    { id: '80', name: 'Israel', prefix: '+972' },
    { id: '81', name: 'Italy', prefix: '+39' },
    { id: '82', name: 'Jamaica', prefix: '+1-876' },
    { id: '83', name: 'Japan', prefix: '+81' },
    { id: '84', name: 'Jordan', prefix: '+962' },
    { id: '85', name: 'Kazakhstan', prefix: '+7' },
    { id: '86', name: 'Kenya', prefix: '+254' },
    { id: '87', name: 'Kiribati', prefix: '+686' },
    { id: '88', name: 'Korea (North)', prefix: '+850' },
    { id: '89', name: 'Korea (South)', prefix: '+82' },
    { id: '90', name: 'Kuwait', prefix: '+965' },
    { id: '91', name: 'Kyrgyzstan', prefix: '+996' },
    { id: '92', name: 'Laos', prefix: '+856' },
    { id: '93', name: 'Latvia', prefix: '+371' },
    { id: '94', name: 'Lebanon', prefix: '+961' },
    { id: '95', name: 'Lesotho', prefix: '+266' },
    { id: '96', name: 'Liberia', prefix: '+231' },
    { id: '97', name: 'Libya', prefix: '+218' },
    { id: '98', name: 'Liechtenstein', prefix: '+423' },
    { id: '99', name: 'Lithuania', prefix: '+370' },
    { id: '100', name: 'Luxembourg', prefix: '+352' },
    { id: '101', name: 'Madagascar', prefix: '+261' },
    { id: '102', name: 'Malawi', prefix: '+265' },
    { id: '103', name: 'Malaysia', prefix: '+60' },
    { id: '104', name: 'Maldives', prefix: '+960' },
    { id: '105', name: 'Mali', prefix: '+223' },
    { id: '106', name: 'Malta', prefix: '+356' },
    { id: '107', name: 'Marshall Islands', prefix: '+692' },
    { id: '108', name: 'Mauritania', prefix: '+222' },
    { id: '109', name: 'Mauritius', prefix: '+230' },
    { id: '110', name: 'Mexico', prefix: '+52' },
    { id: '111', name: 'Micronesia', prefix: '+691' },
    { id: '112', name: 'Moldova', prefix: '+373' },
    { id: '113', name: 'Monaco', prefix: '+377' },
    { id: '114', name: 'Mongolia', prefix: '+976' },
    { id: '115', name: 'Montenegro', prefix: '+382' },
    { id: '116', name: 'Morocco', prefix: '+212' },
    { id: '117', name: 'Mozambique', prefix: '+258' },
    { id: '118', name: 'Myanmar (Burma)', prefix: '+95' },
    { id: '119', name: 'Namibia', prefix: '+264' },
    { id: '120', name: 'Nauru', prefix: '+674' },
    { id: '121', name: 'Nepal', prefix: '+977' },
    { id: '122', name: 'Netherlands', prefix: '+31' },
    { id: '123', name: 'New Zealand', prefix: '+64' },
    { id: '124', name: 'Nicaragua', prefix: '+505' },
    { id: '125', name: 'Niger', prefix: '+227' },
    { id: '126', name: 'Nigeria', prefix: '+234' },
    { id: '127', name: 'North Macedonia', prefix: '+389' },
    { id: '128', name: 'Norway', prefix: '+47' },
    { id: '129', name: 'Oman', prefix: '+968' },
    { id: '130', name: 'Pakistan', prefix: '+92' },
    { id: '131', name: 'Palau', prefix: '+680' },
    { id: '132', name: 'Palestine', prefix: '+970' },
    { id: '133', name: 'Panama', prefix: '+507' },
    { id: '134', name: 'Papua New Guinea', prefix: '+675' },
    { id: '135', name: 'Paraguay', prefix: '+595' },
    { id: '136', name: 'Peru', prefix: '+51' },
    { id: '137', name: 'Philippines', prefix: '+63' },
    { id: '138', name: 'Poland', prefix: '+48' },
    { id: '139', name: 'Portugal', prefix: '+351' },
    { id: '140', name: 'Qatar', prefix: '+974' },
    { id: '141', name: 'Romania', prefix: '+40' },
    { id: '142', name: 'Russia', prefix: '+7' },
    { id: '143', name: 'Rwanda', prefix: '+250' },
    { id: '144', name: 'Saint Kitts and Nevis', prefix: '+1-869' },
    { id: '145', name: 'Saint Lucia', prefix: '+1-758' },
    { id: '146', name: 'Saint Vincent and the Grenadines', prefix: '+1-784' },
    { id: '147', name: 'Samoa', prefix: '+685' },
    { id: '148', name: 'San Marino', prefix: '+378' },
    { id: '149', name: 'Sao Tome and Principe', prefix: '+239' },
    { id: '150', name: 'Saudi Arabia', prefix: '+966' },
    { id: '151', name: 'Senegal', prefix: '+221' },
    { id: '152', name: 'Serbia', prefix: '+381' },
    { id: '153', name: 'Seychelles', prefix: '+248' },
    { id: '154', name: 'Sierra Leone', prefix: '+232' },
    { id: '155', name: 'Singapore', prefix: '+65' },
    { id: '156', name: 'Slovakia', prefix: '+421' },
    { id: '157', name: 'Slovenia', prefix: '+386' },
    { id: '158', name: 'Solomon Islands', prefix: '+677' },
    { id: '159', name: 'Somalia', prefix: '+252' },
    { id: '160', name: 'South Africa', prefix: '+27' },
    { id: '161', name: 'South Sudan', prefix: '+211' },
    { id: '162', name: 'Spain', prefix: '+34' },
    { id: '163', name: 'Sri Lanka', prefix: '+94' },
    { id: '164', name: 'Sudan', prefix: '+249' },
    { id: '165', name: 'Suriname', prefix: '+597' },
    { id: '166', name: 'Sweden', prefix: '+46' },
    { id: '167', name: 'Switzerland', prefix: '+41' },
    { id: '168', name: 'Syria', prefix: '+963' },
    { id: '169', name: 'Taiwan', prefix: '+886' },
    { id: '170', name: 'Tajikistan', prefix: '+992' },
    { id: '171', name: 'Tanzania', prefix: '+255' },
    { id: '172', name: 'Thailand', prefix: '+66' },
    { id: '173', name: 'Timor-Leste', prefix: '+670' },
    { id: '174', name: 'Togo', prefix: '+228' },
    { id: '175', name: 'Tonga', prefix: '+676' },
    { id: '176', name: 'Trinidad and Tobago', prefix: '+1-868' },
    { id: '177', name: 'Tunisia', prefix: '+216' },
    { id: '178', name: 'Turkey', prefix: '+90' },
    { id: '179', name: 'Turkmenistan', prefix: '+993' },
    { id: '180', name: 'Tuvalu', prefix: '+688' },
    { id: '181', name: 'Uganda', prefix: '+256' },
    { id: '182', name: 'Ukraine', prefix: '+380' },
    { id: '183', name: 'United Arab Emirates', prefix: '+971' },
    { id: '184', name: 'United Kingdom', prefix: '+44' },
    { id: '185', name: 'United States', prefix: '+1' },
    { id: '186', name: 'Uruguay', prefix: '+598' },
    { id: '187', name: 'Uzbekistan', prefix: '+998' },
    { id: '188', name: 'Vanuatu', prefix: '+678' },
    { id: '189', name: 'Vatican City', prefix: '+39' },
    { id: '190', name: 'Venezuela', prefix: '+58' },
    { id: '191', name: 'Vietnam', prefix: '+84' },
    { id: '192', name: 'Yemen', prefix: '+967' },
    { id: '193', name: 'Zambia', prefix: '+260' },
    { id: '194', name: 'Zimbabwe', prefix: '+263' }
    ]);
  }
  
}
